name: Test Release
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact
          
      - name: Check downloaded artifact
        run: ls
        
      - name: Get tag version
        id: TagVersion
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
        
      - name: Check tag version
        run: echo ${{ steps.TagVersion.outputs.version }}
        
      - name: Rename artifact
        run: mv pos-mobile ${{ steps.TagVersion.outputs.VERSION }} 
      
      - name: Get change log
        uses: scottbrenner/generate-changelog-action@master
        id: ChangeLog
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.TagVersion.outputs.VERSION }}
          body: ${{ steps.ChangeLog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  
